theme = "gruvbox_light"

[editor]
line-number = "relative"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = false

[editor.cursor-shape]
select = "underline"

[keys.normal]
C-r = ":config-reload"
C-o = ":open ~/.config/helix/config.toml"
space."." = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
backspace = "delete_char_backward"

[keys.normal.n]
c= "@i```c```jjhhhi<ret><ret>jjki<tab>"

[keys.insert.j]
j = "normal_mode"


